# Generated by Django 4.1.13 on 2024-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_feedback_purifiermodel_purifierdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='address',
            name='phonne_number',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
