# Generated by Django 4.1.13 on 2024-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_address_full_name_address_phonne_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phonne_number',
            field=models.CharField(max_length=20),
        ),
    ]
