# Generated by Django 4.1.13 on 2024-06-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_alter_address_phonne_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
    ]
