# Generated by Django 4.1.13 on 2024-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_remove_address_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phonne_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
