# Generated by Django 4.1.13 on 2024-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_service_purifierdetails_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(default=None, upload_to='feedback_images/'),
        ),
    ]
