# Generated by Django 4.1.13 on 2024-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(default=None, upload_to='photos/feedback_images/'),
        ),
    ]
