# Generated by Django 4.1.13 on 2024-07-01 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_alter_feedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('warranty_lastdate', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.FloatField(default=0.0)),
                ('CGST', models.FloatField(default=0.0)),
                ('SGST', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('purifierdetails_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='restapi.purifierdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
