# Generated by Django 4.1.13 on 2024-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_billing_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='warranty_lastdate',
            field=models.DateField(),
        ),
    ]
