# Generated by Django 4.1.13 on 2024-07-01 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_alter_billing_warranty_lastdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='none', max_length=250)),
                ('phone_number', models.CharField(default='none', max_length=15)),
                ('Problem', models.TextField()),
                ('images', models.ImageField(upload_to='photos/Issues_images/')),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
