# Generated by Django 4.1.13 on 2024-07-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_servicing_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicing',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='purifierdetails_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.purifierdetails'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purifierdetails',
            name='purifiermodel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.purifiermodel'),
        ),
    ]
