# Generated by Django 5.0.6 on 2024-10-17 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_alter_billing_warranty_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='warranty_lastdate',
            field=models.DateField(default=datetime.date(2025, 10, 17)),
        ),
    ]
